# Generated by Django 3.0.8 on 2020-07-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=70)),
                ('street', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('männlich', 'male'), ('weiblich', 'female'), ('keins', 'none')], default='keins', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=50)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('desc', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('nprice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_field', models.CharField(max_length=6)),
                ('date', models.DateField()),
                ('taxes', models.FloatField(default=0.19)),
                ('number', models.CharField(max_length=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Customer')),
                ('parts', models.ManyToManyField(to='bills.Part')),
            ],
        ),
    ]
